// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"go_confess_space-project/api/controller"
	"go_confess_space-project/api/repository"
	"go_confess_space-project/api/service"
	"go_confess_space-project/config"
)

// Injectors from injector.go:

func SpaceInjector() *controller.SpaceController {
	db := config.DatabaseConnection()
	spaceRepository := repository.NewSpaceRepositoryImpl(db)
	validate := config.Validator()
	spaceService := service.NewSpaceServiceImpl(spaceRepository, validate)
	spaceController := controller.NewSpaceAuthController(spaceService)
	return spaceController
}

func UserSpaceInjector() *controller.UserSpaceController {
	db := config.DatabaseConnection()
	userSpaceRepository := repository.NewUserSpaceRepositoryImpl(db)
	validate := config.Validator()
	userSpaceService := service.NewUserSpaceServiceImpl(userSpaceRepository, validate)
	userSpaceController := controller.NewUserSpaceController(userSpaceService)
	return userSpaceController
}

func MessageInjector() *controller.MessageController {
	db := config.DatabaseConnection()
	messageRepository := repository.NewMessageRepositoryImpl(db)
	validate := config.Validator()
	messageService := service.NewMessageServiceImpl(messageRepository, validate)
	messageController := controller.NewMessageController(messageService)
	return messageController
}

func UserSpaceLastSeenInjector() *controller.UserSpaceLastSeenController {
	db := config.DatabaseConnection()
	userSpaceLastSeenRepository := repository.NewUserSpaceLastSeenRepositoryImpl(db)
	validate := config.Validator()
	userSpaceLastSeenService := service.NewUserSpaceLastSeenServiceImpl(userSpaceLastSeenRepository, validate)
	userSpaceLastSeenController := controller.NewUserSpaceLastSeenController(userSpaceLastSeenService)
	return userSpaceLastSeenController
}

func UserSpaceLastSeenInjectorWithAuth() *controller.UserSpaceLastSeenController {
	db := config.DatabaseConnection()
	userSpaceLastSeenRepository := repository.NewUserSpaceLastSeenRepositoryImpl(db)
	validate := config.Validator()
	userSpaceLastSeenService := service.NewUserSpaceLastSeenServiceImpl(userSpaceLastSeenRepository, validate)
	userSpaceLastSeenController := controller.NewUserSpaceLastSeenController(userSpaceLastSeenService)
	return userSpaceLastSeenController
}
